import React from "react";
import Head from "next/head";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Welcome — My Workspace App</title>
        <meta name="description" content="Scaffolded Next + Tailwind + SASS starter generated by the scaffold." />
      </Head>
      <main className="homepage">
        <section className="hero">
          <h1 className="hero-title">My Workspace</h1>
          <p className="hero-subtitle">A ready-to-run Next + Tailwind + SASS starter generated by the scaffold.</p>
          <div className="hero-actions">
            <Link href="/dashboard" className="btn btn-primary">Go to Dashboard</Link>
            <Link href="/about" className="btn btn-secondary">About</Link>
            <Link href="/login" className="btn btn-text">Login</Link>
          </div>
        </section>
      </main>
    </>
  );
}
